/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeagenda.ui;

import java.sql.Array;
import java.util.ArrayList;
import java.util.List;
import sistemadeagenda.controller.CitaController;
import sistemadeagenda.controller.LocacionController;
import sistemadeagenda.controller.PersonaController;
import sistemadeagenda.controller.TipoDeEventoController;
import sistemadeagenda.objects.Cita;
import sistemadeagenda.objects.Locacion;
import sistemadeagenda.objects.Persona;
import sistemadeagenda.objects.TipoDeEvento;

/**
 *
 * @author Seba-PC
 */
public class CrudCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrudCita
     */
    PersonaController personaController;
    LocacionController locacionController;
    TipoDeEventoController tipoDeEventoController;
    CitaController citaController;
    Integer auxIdAnfitrion=1;
    Integer auxIdLocacion=1;
    Integer auxIdTipoEvento=1;
    Integer auxIdAgenda=1;
    
    public CrudCita() {
        initComponents();
       
        citaController = new CitaController();
        //Inicializacion persona
        personaController = new PersonaController();
        List<Persona> anfitriones =this.personaController.getAllAnfitrion();
       
        for (int i = 0; i < anfitriones.size(); i++) {
            Persona persona = new Persona();
            persona.setNombre(anfitriones.get(i).getNombre());
            jcbNombreAnfitrion.addItem(persona.getNombre());
        } 
        
        //Inicializacion Locacion
        locacionController = new LocacionController();
        List<Locacion> locaciones =this.locacionController.getAllObjects();
       
        for (int i = 0; i < locaciones.size(); i++) {
            Locacion locacion = new Locacion();
            locacion.setDomicilio(locaciones.get(i).getDomicilio());
            jcbDomicilio.addItem(locacion.getDomicilio());
        } 
        
        //Inicializacion Tipo de Evento
        tipoDeEventoController = new TipoDeEventoController();
        List<TipoDeEvento> tipoeventos =this.tipoDeEventoController.getAllObjects();
       
        for (int i = 0; i < tipoeventos.size(); i++) {
            TipoDeEvento tipoevento = new TipoDeEvento();
            tipoevento.setNombre(tipoeventos.get(i).getNombre());
            jcbTipoEvento.addItem(tipoevento.getNombre());
        } 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbNombreAnfitrion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jbtnCrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcbDomicilio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbTipoEvento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtfFecha = new javax.swing.JTextField();
        jtfAnfitrion = new javax.swing.JTextField();
        jtfTipoEvento = new javax.swing.JTextField();
        jtfDomicilio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jcbNombreAnfitrion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNombreAnfitrionActionPerformed(evt);
            }
        });

        jLabel2.setText("Domicilio:");

        jbtnCrear.setText("Crear");
        jbtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel3.setText("CRUD CITA");

        jLabel1.setText("Anfitrion:");

        jcbDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDomicilioActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Evento:");

        jcbTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoEventoActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha y Hora:");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jcbDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbNombreAnfitrion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbTipoEvento, 0, 173, Short.MAX_VALUE)
                            .addComponent(jtfFecha)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbNombreAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbNombreAnfitrionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNombreAnfitrionActionPerformed
        String auxAnfitrion = jcbNombreAnfitrion.getSelectedItem().toString();
        
        
       personaController = new PersonaController();
        List<Persona> anfitriones =this.personaController.getAllAnfitrion();
       
        for (int i = 0; i < anfitriones.size(); i++) {
            if((anfitriones.get(i).getNombre()).equals(auxAnfitrion)){
                auxIdAnfitrion = anfitriones.get(i).getId();
            }
        }
        
      jtfAnfitrion.setText(auxIdAnfitrion.toString());
        
    }//GEN-LAST:event_jcbNombreAnfitrionActionPerformed

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
   
        Cita cita = new Cita(auxIdAgenda,auxIdLocacion,auxIdTipoEvento,jtfFecha.getText(),jcbDomicilio.getSelectedItem().toString(),auxIdAnfitrion,jcbTipoEvento.getSelectedItem().toString());
        this.citaController.insertObject(cita);
        
    }//GEN-LAST:event_jbtnCrearActionPerformed

    private void jcbDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDomicilioActionPerformed
        
        String auxDomicilio = jcbDomicilio.getSelectedItem().toString();
        
        
       locacionController = new LocacionController();
        List<Locacion> locaciones =this.locacionController.getAllObjects();
   
        for (int i = 0; i < locaciones.size(); i++) {
            if((locaciones.get(i).getDomicilio()).equals(auxDomicilio)){
                Locacion locacion1 = new Locacion();
                locacion1.setNombre(locaciones.get(i).getDomicilio());
                auxIdLocacion = locaciones.get(i).getId();
            }
        }
        
        jtfDomicilio.setText(auxIdLocacion.toString());
        
    }//GEN-LAST:event_jcbDomicilioActionPerformed

    private void jcbTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoEventoActionPerformed
        String auxTipoEvento = jcbTipoEvento.getSelectedItem().toString();
        
        
       tipoDeEventoController = new TipoDeEventoController();
        List<TipoDeEvento> eventos =this.tipoDeEventoController.getAllObjects();
       
        for (int i = 0; i < eventos.size(); i++) {
            if((eventos.get(i).getNombre()).equals(auxTipoEvento)){
                auxIdTipoEvento = eventos.get(i).getId();
            }
        }
        
         jtfTipoEvento.setText(auxIdTipoEvento.toString());
        
    }//GEN-LAST:event_jcbTipoEventoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Principal principal = new Principal();
        principal.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JComboBox<String> jcbDomicilio;
    private javax.swing.JComboBox<String> jcbNombreAnfitrion;
    private javax.swing.JComboBox<String> jcbTipoEvento;
    private javax.swing.JTextField jtfAnfitrion;
    private javax.swing.JTextField jtfDomicilio;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfTipoEvento;
    // End of variables declaration//GEN-END:variables
}
